//
// Created by diegorenner on 5/21/20.
//

#ifndef HELMHOLTZTRANSMISSIONPROBLEM_GEN_SOL_OP_HPP
#define HELMHOLTZTRANSMISSIONPROBLEM_GEN_SOL_OP_HPP

#endif //HELMHOLTZTRANSMISSIONPROBLEM_GEN_SOL_OP_HPP
