//
// Created by diegorenner on 2/20/20.
//

#ifndef HELMHOLTZTRANSMISSIONPROBLEM_HYPERSINGULAR_SMOOTH_TEST_HPP
#define HELMHOLTZTRANSMISSIONPROBLEM_HYPERSINGULAR_SMOOTH_TEST_HPP

#include "hypersingular.hpp"

#endif //HELMHOLTZTRANSMISSIONPROBLEM_SMOOTH_HYPERSINGULAR_TEST_HPP
