//
// Created by diegorenner on 2/20/20.
//

#ifndef HELMHOLTZTRANSMISSIONPROBLEM_SOLUTIONS_TEST_HPP
#define HELMHOLTZTRANSMISSIONPROBLEM_SOLUTIONS_TEST_HPP

#include "generate_solution.hpp"

#endif //HELMHOLTZTRANSMISSIONPROBLEM_SOLUTIONS_TEST_HPP
